export const translateOrderItemKeys = {
  internalId: 'Nr TXI',
  status: 'Status',
  externalId: 'Nr zlecenia',
  estimatedDistance: 'Szacowane km',
  kmForDriver: 'km dla kierowcy',
  actualKm: 'Rzeczywiste km',
  clientName: 'Nazwa klienta',
  clientInvoice: 'Faktura klienta',
  isPayed: 'Faktura opłacona',
  driver: 'Kierowca',
  driverInvoice: 'Faktura kierowcy',
  collectionPoint: 'Punkt zborny',
  locationFrom: 'Miejsce odbioru',
  locationTo: 'Miejsce docelowe',
  locationVia: 'Lokalizacje przez',
  stopTime: 'Czas oczekiwania',
  highwaysCost: 'Koszt płatnych odcinków',
  createdAt: 'Data utworzenia zlecenia',
  updatedAt: 'Data ostatniej aktualizacji',
};
